######################################################################
# Automatically generated by qmake (2.01a) H márc. 25 08:28:40 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sejtablak.h sejtszal.h
SOURCES += main.cpp sejtablak.cpp sejtszal.cpp
